/**
 * UICombo.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.component.form.impl;

import org.operamasks.faces.component.form.base.UIComboBase;

@javax.annotation.Generated(value="org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory", date="2012-11-03T15:46:26Z")
public class UICombo extends UIComboBase {
    public static final String COMPONENT_FAMILY = "org.operamasks.faces.component.form.impl.UICombo";
    public static final String COMPONENT_TYPE = "org.operamasks.faces.component.form.impl.UICombo";

    public UICombo() {
	super.setRendererType("org.operamasks.faces.component.form.impl.UICombo");
    }

    public String getFamily() {
	return COMPONENT_FAMILY;
    }

    public java.lang.String getAllQuery() {
	if (this.allQuery != null) {
	    return this.allQuery;
	}
	javax.el.ValueExpression ve = this.getValueExpression("allQuery");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setAllQuery(java.lang.String value) {
	this.allQuery = value;
    }

    public java.lang.String getDisplayField() {
	if (this.displayField != null) {
	    return this.displayField;
	}
	javax.el.ValueExpression ve = this.getValueExpression("displayField");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setDisplayField(java.lang.String value) {
	this.displayField = value;
    }

    public java.lang.Boolean getEditable() {
	if (this.editable != null) {
	    return this.editable;
	}
	javax.el.ValueExpression ve = this.getValueExpression("editable");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setEditable(java.lang.Boolean value) {
	this.editable = value;
    }

    public java.lang.Boolean getForceSelection() {
	if (this.forceSelection != null) {
	    return this.forceSelection;
	}
	javax.el.ValueExpression ve = this.getValueExpression("forceSelection");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setForceSelection(java.lang.Boolean value) {
	this.forceSelection = value;
    }

    public java.lang.Integer getHandleHeight() {
	if (this.handleHeight != null) {
	    return this.handleHeight;
	}
	javax.el.ValueExpression ve = this.getValueExpression("handleHeight");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setHandleHeight(java.lang.Integer value) {
	this.handleHeight = value;
    }

    public java.lang.String getHiddenName() {
	if (this.hiddenName != null) {
	    return this.hiddenName;
	}
	javax.el.ValueExpression ve = this.getValueExpression("hiddenName");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setHiddenName(java.lang.String value) {
	this.hiddenName = value;
    }

    public java.lang.Boolean getLazyInit() {
	if (this.lazyInit != null) {
	    return this.lazyInit;
	}
	javax.el.ValueExpression ve = this.getValueExpression("lazyInit");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setLazyInit(java.lang.Boolean value) {
	this.lazyInit = value;
    }

    public java.lang.Boolean getLazyRender() {
	if (this.lazyRender != null) {
	    return this.lazyRender;
	}
	javax.el.ValueExpression ve = this.getValueExpression("lazyRender");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setLazyRender(java.lang.Boolean value) {
	this.lazyRender = value;
    }

    public java.lang.String getListAlign() {
	if (this.listAlign != null) {
	    return this.listAlign;
	}
	javax.el.ValueExpression ve = this.getValueExpression("listAlign");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setListAlign(java.lang.String value) {
	this.listAlign = value;
    }

    public java.lang.String getListClass() {
	if (this.listClass != null) {
	    return this.listClass;
	}
	javax.el.ValueExpression ve = this.getValueExpression("listClass");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setListClass(java.lang.String value) {
	this.listClass = value;
    }

    public java.lang.Integer getListWidth() {
	if (this.listWidth != null) {
	    return this.listWidth;
	}
	javax.el.ValueExpression ve = this.getValueExpression("listWidth");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setListWidth(java.lang.Integer value) {
	this.listWidth = value;
    }

    public java.lang.String getLoadingText() {
	if (this.loadingText != null) {
	    return this.loadingText;
	}
	javax.el.ValueExpression ve = this.getValueExpression("loadingText");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setLoadingText(java.lang.String value) {
	this.loadingText = value;
    }

    public java.lang.Integer getMinChars() {
	if (this.minChars != null) {
	    return this.minChars;
	}
	javax.el.ValueExpression ve = this.getValueExpression("minChars");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setMinChars(java.lang.Integer value) {
	this.minChars = value;
    }

    public java.lang.Integer getMinListWidth() {
	if (this.minListWidth != null) {
	    return this.minListWidth;
	}
	javax.el.ValueExpression ve = this.getValueExpression("minListWidth");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setMinListWidth(java.lang.Integer value) {
	this.minListWidth = value;
    }

    public java.lang.String getMode() {
	if (this.mode != null) {
	    return this.mode;
	}
	javax.el.ValueExpression ve = this.getValueExpression("mode");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setMode(java.lang.String value) {
	this.mode = value;
    }

    public java.lang.Integer getPageSize() {
	if (this.pageSize != null) {
	    return this.pageSize;
	}
	javax.el.ValueExpression ve = this.getValueExpression("pageSize");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setPageSize(java.lang.Integer value) {
	this.pageSize = value;
    }

    public java.lang.Integer getQueryDelay() {
	if (this.queryDelay != null) {
	    return this.queryDelay;
	}
	javax.el.ValueExpression ve = this.getValueExpression("queryDelay");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setQueryDelay(java.lang.Integer value) {
	this.queryDelay = value;
    }

    public java.lang.String getQueryParam() {
	if (this.queryParam != null) {
	    return this.queryParam;
	}
	javax.el.ValueExpression ve = this.getValueExpression("queryParam");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setQueryParam(java.lang.String value) {
	this.queryParam = value;
    }

    public java.lang.Boolean getResizable() {
	if (this.resizable != null) {
	    return this.resizable;
	}
	javax.el.ValueExpression ve = this.getValueExpression("resizable");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setResizable(java.lang.Boolean value) {
	this.resizable = value;
    }

    public java.lang.Boolean getSelectOnFocus() {
	if (this.selectOnFocus != null) {
	    return this.selectOnFocus;
	}
	javax.el.ValueExpression ve = this.getValueExpression("selectOnFocus");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setSelectOnFocus(java.lang.Boolean value) {
	this.selectOnFocus = value;
    }

    public java.lang.String getSelectedClass() {
	if (this.selectedClass != null) {
	    return this.selectedClass;
	}
	javax.el.ValueExpression ve = this.getValueExpression("selectedClass");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setSelectedClass(java.lang.String value) {
	this.selectedClass = value;
    }

    public java.lang.String getShadow() {
	if (this.shadow != null) {
	    return this.shadow;
	}
	javax.el.ValueExpression ve = this.getValueExpression("shadow");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setShadow(java.lang.String value) {
	this.shadow = value;
    }

    public java.lang.String getTitle() {
	if (this.title != null) {
	    return this.title;
	}
	javax.el.ValueExpression ve = this.getValueExpression("title");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTitle(java.lang.String value) {
	this.title = value;
    }

    public java.lang.String getTpl() {
	if (this.tpl != null) {
	    return this.tpl;
	}
	javax.el.ValueExpression ve = this.getValueExpression("tpl");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTpl(java.lang.String value) {
	this.tpl = value;
    }

    public java.lang.String getTransform() {
	if (this.transform != null) {
	    return this.transform;
	}
	javax.el.ValueExpression ve = this.getValueExpression("transform");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTransform(java.lang.String value) {
	this.transform = value;
    }

    public java.lang.String getTriggerAction() {
	if (this.triggerAction != null) {
	    return this.triggerAction;
	}
	javax.el.ValueExpression ve = this.getValueExpression("triggerAction");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTriggerAction(java.lang.String value) {
	this.triggerAction = value;
    }

    public java.lang.String getTriggerClass() {
	if (this.triggerClass != null) {
	    return this.triggerClass;
	}
	javax.el.ValueExpression ve = this.getValueExpression("triggerClass");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTriggerClass(java.lang.String value) {
	this.triggerClass = value;
    }

    public java.lang.Boolean getTypeAhead() {
	if (this.typeAhead != null) {
	    return this.typeAhead;
	}
	javax.el.ValueExpression ve = this.getValueExpression("typeAhead");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTypeAhead(java.lang.Boolean value) {
	this.typeAhead = value;
    }

    public java.lang.Integer getTypeAheadDelay() {
	if (this.typeAheadDelay != null) {
	    return this.typeAheadDelay;
	}
	javax.el.ValueExpression ve = this.getValueExpression("typeAheadDelay");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTypeAheadDelay(java.lang.Integer value) {
	this.typeAheadDelay = value;
    }

    public java.lang.String getValueField() {
	if (this.valueField != null) {
	    return this.valueField;
	}
	javax.el.ValueExpression ve = this.getValueExpression("valueField");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setValueField(java.lang.String value) {
	this.valueField = value;
    }

    public java.lang.String getValueNotFoundText() {
	if (this.valueNotFoundText != null) {
	    return this.valueNotFoundText;
	}
	javax.el.ValueExpression ve = this.getValueExpression("valueNotFoundText");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setValueNotFoundText(java.lang.String value) {
	this.valueNotFoundText = value;
    }

    public java.lang.String getOncollapse() {
	if (this.oncollapse != null) {
	    return this.oncollapse;
	}
	javax.el.ValueExpression ve = this.getValueExpression("oncollapse");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setOncollapse(java.lang.String value) {
	this.oncollapse = value;
    }

    public java.lang.String getOnexpand() {
	if (this.onexpand != null) {
	    return this.onexpand;
	}
	javax.el.ValueExpression ve = this.getValueExpression("onexpand");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setOnexpand(java.lang.String value) {
	this.onexpand = value;
    }

    public java.lang.String getOnselect() {
	if (this.onselect != null) {
	    return this.onselect;
	}
	javax.el.ValueExpression ve = this.getValueExpression("onselect");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setOnselect(java.lang.String value) {
	this.onselect = value;
    }

    public Object saveState(javax.faces.context.FacesContext context) {
	return new Object[] {
	    super.saveState(context),
	    this.allQuery,
	    this.displayField,
	    this.editable,
	    this.forceSelection,
	    this.handleHeight,
	    this.hiddenName,
	    this.lazyInit,
	    this.lazyRender,
	    this.listAlign,
	    this.listClass,
	    this.listWidth,
	    this.loadingText,
	    this.minChars,
	    this.minListWidth,
	    this.mode,
	    this.pageSize,
	    this.queryDelay,
	    this.queryParam,
	    this.resizable,
	    this.selectOnFocus,
	    this.selectedClass,
	    this.shadow,
	    this.title,
	    this.tpl,
	    this.transform,
	    this.triggerAction,
	    this.triggerClass,
	    this.typeAhead,
	    this.typeAheadDelay,
	    this.valueField,
	    this.valueNotFoundText,
	    this.oncollapse,
	    this.onexpand,
	    this.onselect,
	};
    }

    public void restoreState(javax.faces.context.FacesContext context, Object state) {
	Object[] values = (Object[])state;
	super.restoreState(context, values[0]);
	this.allQuery = (java.lang.String)values[1];
	this.displayField = (java.lang.String)values[2];
	this.editable = (java.lang.Boolean)values[3];
	this.forceSelection = (java.lang.Boolean)values[4];
	this.handleHeight = (java.lang.Integer)values[5];
	this.hiddenName = (java.lang.String)values[6];
	this.lazyInit = (java.lang.Boolean)values[7];
	this.lazyRender = (java.lang.Boolean)values[8];
	this.listAlign = (java.lang.String)values[9];
	this.listClass = (java.lang.String)values[10];
	this.listWidth = (java.lang.Integer)values[11];
	this.loadingText = (java.lang.String)values[12];
	this.minChars = (java.lang.Integer)values[13];
	this.minListWidth = (java.lang.Integer)values[14];
	this.mode = (java.lang.String)values[15];
	this.pageSize = (java.lang.Integer)values[16];
	this.queryDelay = (java.lang.Integer)values[17];
	this.queryParam = (java.lang.String)values[18];
	this.resizable = (java.lang.Boolean)values[19];
	this.selectOnFocus = (java.lang.Boolean)values[20];
	this.selectedClass = (java.lang.String)values[21];
	this.shadow = (java.lang.String)values[22];
	this.title = (java.lang.String)values[23];
	this.tpl = (java.lang.String)values[24];
	this.transform = (java.lang.String)values[25];
	this.triggerAction = (java.lang.String)values[26];
	this.triggerClass = (java.lang.String)values[27];
	this.typeAhead = (java.lang.Boolean)values[28];
	this.typeAheadDelay = (java.lang.Integer)values[29];
	this.valueField = (java.lang.String)values[30];
	this.valueNotFoundText = (java.lang.String)values[31];
	this.oncollapse = (java.lang.String)values[32];
	this.onexpand = (java.lang.String)values[33];
	this.onselect = (java.lang.String)values[34];
    }

}
