/**
 * UIRadioGroup.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.component.form.impl;

import org.operamasks.faces.component.form.base.UIRadioGroupBase;

@javax.annotation.Generated(value="org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory", date="2012-11-03T15:46:26Z")
public class UIRadioGroup extends UIRadioGroupBase {
    public static final String COMPONENT_TYPE = "org.operamasks.faces.component.form.impl.UIRadioGroup";

    public UIRadioGroup() {
	super.setRendererType("org.operamasks.faces.component.form.impl.UIRadioGroup");
    }

    public java.lang.String getDirection() {
	if (this.direction != null) {
	    return this.direction;
	}
	javax.el.ValueExpression ve = this.getValueExpression("direction");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setDirection(java.lang.String value) {
	this.direction = value;
    }

    public java.lang.String getOnchange() {
	if (this.onchange != null) {
	    return this.onchange;
	}
	javax.el.ValueExpression ve = this.getValueExpression("onchange");
	if (ve != null) {
	    try {
		return (java.lang.String)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setOnchange(java.lang.String value) {
	this.onchange = value;
    }

    public Object saveState(javax.faces.context.FacesContext context) {
	return new Object[] {
	    super.saveState(context),
	    this.direction,
	    this.onchange,
	};
    }

    public void restoreState(javax.faces.context.FacesContext context, Object state) {
	Object[] values = (Object[])state;
	super.restoreState(context, values[0]);
	this.direction = (java.lang.String)values[1];
	this.onchange = (java.lang.String)values[2];
    }

}
