/**
 * UITextArea.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.component.form.impl;

import org.operamasks.faces.component.form.base.UITextAreaBase;

@javax.annotation.Generated(value="org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory", date="2012-11-03T15:46:26Z")
public class UITextArea extends UITextAreaBase {
    public static final String COMPONENT_FAMILY = "org.operamasks.faces.component.form.impl.UITextArea";
    public static final String COMPONENT_TYPE = "org.operamasks.faces.component.form.impl.UITextArea";

    public UITextArea() {
	super.setRendererType("org.operamasks.faces.component.form.impl.UITextArea");
    }

    public String getFamily() {
	return COMPONENT_FAMILY;
    }

    public java.lang.Integer getGrowMax() {
	if (this.growMax != null) {
	    return this.growMax;
	}
	javax.el.ValueExpression ve = this.getValueExpression("growMax");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setGrowMax(java.lang.Integer value) {
	this.growMax = value;
    }

    public java.lang.Integer getGrowMin() {
	if (this.growMin != null) {
	    return this.growMin;
	}
	javax.el.ValueExpression ve = this.getValueExpression("growMin");
	if (ve != null) {
	    try {
		return (java.lang.Integer)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setGrowMin(java.lang.Integer value) {
	this.growMin = value;
    }

    public java.lang.Boolean getPreventScrollbars() {
	if (this.preventScrollbars != null) {
	    return this.preventScrollbars;
	}
	javax.el.ValueExpression ve = this.getValueExpression("preventScrollbars");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setPreventScrollbars(java.lang.Boolean value) {
	this.preventScrollbars = value;
    }

    public Object saveState(javax.faces.context.FacesContext context) {
	return new Object[] {
	    super.saveState(context),
	    this.growMax,
	    this.growMin,
	    this.preventScrollbars,
	};
    }

    public void restoreState(javax.faces.context.FacesContext context, Object state) {
	Object[] values = (Object[])state;
	super.restoreState(context, values[0]);
	this.growMax = (java.lang.Integer)values[1];
	this.growMin = (java.lang.Integer)values[2];
	this.preventScrollbars = (java.lang.Boolean)values[3];
    }

}
