/**
 * UICheckBox.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

/**
* @jsp.tag name="checkBox" body-content="JSP"
*/
public class UICheckBoxTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UICheckBox";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UICheckBox";
    }

    private javax.el.ValueExpression boxLabel;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setBoxLabel(javax.el.ValueExpression value) {
	this.boxLabel = value;
    }
    private javax.el.ValueExpression checked;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setChecked(javax.el.ValueExpression value) {
	this.checked = value;
    }
    private javax.el.ValueExpression fieldClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFieldClass(javax.el.ValueExpression value) {
	this.fieldClass = value;
    }
    private javax.el.ValueExpression focusClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFocusClass(javax.el.ValueExpression value) {
	this.focusClass = value;
    }
    private javax.el.ValueExpression inputValue;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setInputValue(javax.el.ValueExpression value) {
	this.inputValue = value;
    }
    private javax.el.ValueExpression oncheck;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOncheck(javax.el.ValueExpression value) {
	this.oncheck = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("boxLabel", this.boxLabel);
	c.setValueExpression("checked", this.checked);
	c.setValueExpression("fieldClass", this.fieldClass);
	c.setValueExpression("focusClass", this.focusClass);
	c.setValueExpression("inputValue", this.inputValue);
	c.setValueExpression("oncheck", this.oncheck);
    }

    public void release() {
	super.release();
	this.boxLabel = null;
	this.checked = null;
	this.fieldClass = null;
	this.focusClass = null;
	this.inputValue = null;
	this.oncheck = null;
    }

}
