/**
 * UICombo.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

/**
* @jsp.tag name="combo" body-content="JSP"
*/
public class UIComboTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UICombo";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UICombo";
    }

    private javax.el.ValueExpression allQuery;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setAllQuery(javax.el.ValueExpression value) {
	this.allQuery = value;
    }
    private javax.el.ValueExpression displayField;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setDisplayField(javax.el.ValueExpression value) {
	this.displayField = value;
    }
    private javax.el.ValueExpression editable;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEditable(javax.el.ValueExpression value) {
	this.editable = value;
    }
    private javax.el.ValueExpression forceSelection;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setForceSelection(javax.el.ValueExpression value) {
	this.forceSelection = value;
    }
    private javax.el.ValueExpression handleHeight;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setHandleHeight(javax.el.ValueExpression value) {
	this.handleHeight = value;
    }
    private javax.el.ValueExpression hiddenName;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setHiddenName(javax.el.ValueExpression value) {
	this.hiddenName = value;
    }
    private javax.el.ValueExpression lazyInit;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setLazyInit(javax.el.ValueExpression value) {
	this.lazyInit = value;
    }
    private javax.el.ValueExpression lazyRender;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setLazyRender(javax.el.ValueExpression value) {
	this.lazyRender = value;
    }
    private javax.el.ValueExpression listAlign;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setListAlign(javax.el.ValueExpression value) {
	this.listAlign = value;
    }
    private javax.el.ValueExpression listClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setListClass(javax.el.ValueExpression value) {
	this.listClass = value;
    }
    private javax.el.ValueExpression listWidth;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setListWidth(javax.el.ValueExpression value) {
	this.listWidth = value;
    }
    private javax.el.ValueExpression loadingText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setLoadingText(javax.el.ValueExpression value) {
	this.loadingText = value;
    }
    private javax.el.ValueExpression minChars;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMinChars(javax.el.ValueExpression value) {
	this.minChars = value;
    }
    private javax.el.ValueExpression minListWidth;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMinListWidth(javax.el.ValueExpression value) {
	this.minListWidth = value;
    }
    private javax.el.ValueExpression mode;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMode(javax.el.ValueExpression value) {
	this.mode = value;
    }
    private javax.el.ValueExpression pageSize;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setPageSize(javax.el.ValueExpression value) {
	this.pageSize = value;
    }
    private javax.el.ValueExpression queryDelay;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setQueryDelay(javax.el.ValueExpression value) {
	this.queryDelay = value;
    }
    private javax.el.ValueExpression queryParam;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setQueryParam(javax.el.ValueExpression value) {
	this.queryParam = value;
    }
    private javax.el.ValueExpression resizable;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setResizable(javax.el.ValueExpression value) {
	this.resizable = value;
    }
    private javax.el.ValueExpression selectOnFocus;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setSelectOnFocus(javax.el.ValueExpression value) {
	this.selectOnFocus = value;
    }
    private javax.el.ValueExpression selectedClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setSelectedClass(javax.el.ValueExpression value) {
	this.selectedClass = value;
    }
    private javax.el.ValueExpression shadow;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setShadow(javax.el.ValueExpression value) {
	this.shadow = value;
    }
    private javax.el.ValueExpression title;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTitle(javax.el.ValueExpression value) {
	this.title = value;
    }
    private javax.el.ValueExpression tpl;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTpl(javax.el.ValueExpression value) {
	this.tpl = value;
    }
    private javax.el.ValueExpression transform;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTransform(javax.el.ValueExpression value) {
	this.transform = value;
    }
    private javax.el.ValueExpression triggerAction;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTriggerAction(javax.el.ValueExpression value) {
	this.triggerAction = value;
    }
    private javax.el.ValueExpression triggerClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTriggerClass(javax.el.ValueExpression value) {
	this.triggerClass = value;
    }
    private javax.el.ValueExpression typeAhead;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setTypeAhead(javax.el.ValueExpression value) {
	this.typeAhead = value;
    }
    private javax.el.ValueExpression typeAheadDelay;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setTypeAheadDelay(javax.el.ValueExpression value) {
	this.typeAheadDelay = value;
    }
    private javax.el.ValueExpression valueField;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setValueField(javax.el.ValueExpression value) {
	this.valueField = value;
    }
    private javax.el.ValueExpression valueNotFoundText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setValueNotFoundText(javax.el.ValueExpression value) {
	this.valueNotFoundText = value;
    }
    private javax.el.ValueExpression oncollapse;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOncollapse(javax.el.ValueExpression value) {
	this.oncollapse = value;
    }
    private javax.el.ValueExpression onexpand;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnexpand(javax.el.ValueExpression value) {
	this.onexpand = value;
    }
    private javax.el.ValueExpression onselect;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnselect(javax.el.ValueExpression value) {
	this.onselect = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("allQuery", this.allQuery);
	c.setValueExpression("displayField", this.displayField);
	c.setValueExpression("editable", this.editable);
	c.setValueExpression("forceSelection", this.forceSelection);
	c.setValueExpression("handleHeight", this.handleHeight);
	c.setValueExpression("hiddenName", this.hiddenName);
	c.setValueExpression("lazyInit", this.lazyInit);
	c.setValueExpression("lazyRender", this.lazyRender);
	c.setValueExpression("listAlign", this.listAlign);
	c.setValueExpression("listClass", this.listClass);
	c.setValueExpression("listWidth", this.listWidth);
	c.setValueExpression("loadingText", this.loadingText);
	c.setValueExpression("minChars", this.minChars);
	c.setValueExpression("minListWidth", this.minListWidth);
	c.setValueExpression("mode", this.mode);
	c.setValueExpression("pageSize", this.pageSize);
	c.setValueExpression("queryDelay", this.queryDelay);
	c.setValueExpression("queryParam", this.queryParam);
	c.setValueExpression("resizable", this.resizable);
	c.setValueExpression("selectOnFocus", this.selectOnFocus);
	c.setValueExpression("selectedClass", this.selectedClass);
	c.setValueExpression("shadow", this.shadow);
	c.setValueExpression("title", this.title);
	c.setValueExpression("tpl", this.tpl);
	c.setValueExpression("transform", this.transform);
	c.setValueExpression("triggerAction", this.triggerAction);
	c.setValueExpression("triggerClass", this.triggerClass);
	c.setValueExpression("typeAhead", this.typeAhead);
	c.setValueExpression("typeAheadDelay", this.typeAheadDelay);
	c.setValueExpression("valueField", this.valueField);
	c.setValueExpression("valueNotFoundText", this.valueNotFoundText);
	c.setValueExpression("oncollapse", this.oncollapse);
	c.setValueExpression("onexpand", this.onexpand);
	c.setValueExpression("onselect", this.onselect);
    }

    public void release() {
	super.release();
	this.allQuery = null;
	this.displayField = null;
	this.editable = null;
	this.forceSelection = null;
	this.handleHeight = null;
	this.hiddenName = null;
	this.lazyInit = null;
	this.lazyRender = null;
	this.listAlign = null;
	this.listClass = null;
	this.listWidth = null;
	this.loadingText = null;
	this.minChars = null;
	this.minListWidth = null;
	this.mode = null;
	this.pageSize = null;
	this.queryDelay = null;
	this.queryParam = null;
	this.resizable = null;
	this.selectOnFocus = null;
	this.selectedClass = null;
	this.shadow = null;
	this.title = null;
	this.tpl = null;
	this.transform = null;
	this.triggerAction = null;
	this.triggerClass = null;
	this.typeAhead = null;
	this.typeAheadDelay = null;
	this.valueField = null;
	this.valueNotFoundText = null;
	this.oncollapse = null;
	this.onexpand = null;
	this.onselect = null;
    }

}
