/**
 * UIField.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

public class UIFieldTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UIField";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UIField";
    }

    private javax.el.ValueExpression autoCreate;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setAutoCreate(javax.el.ValueExpression value) {
	this.autoCreate = value;
    }
    private javax.el.ValueExpression clearCls;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setClearCls(javax.el.ValueExpression value) {
	this.clearCls = value;
    }
    private javax.el.ValueExpression cls;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setCls(javax.el.ValueExpression value) {
	this.cls = value;
    }
    private javax.el.ValueExpression disabled;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setDisabled(javax.el.ValueExpression value) {
	this.disabled = value;
    }
    private javax.el.ValueExpression fieldClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFieldClass(javax.el.ValueExpression value) {
	this.fieldClass = value;
    }
    private javax.el.ValueExpression fieldLabel;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFieldLabel(javax.el.ValueExpression value) {
	this.fieldLabel = value;
    }
    private javax.el.ValueExpression focusClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFocusClass(javax.el.ValueExpression value) {
	this.focusClass = value;
    }
    private javax.el.ValueExpression hideLabel;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideLabel(javax.el.ValueExpression value) {
	this.hideLabel = value;
    }
    private javax.el.ValueExpression inputType;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setInputType(javax.el.ValueExpression value) {
	this.inputType = value;
    }
    private javax.el.ValueExpression invalidClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setInvalidClass(javax.el.ValueExpression value) {
	this.invalidClass = value;
    }
    private javax.el.ValueExpression invalidText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setInvalidText(javax.el.ValueExpression value) {
	this.invalidText = value;
    }
    private javax.el.ValueExpression itemCls;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setItemCls(javax.el.ValueExpression value) {
	this.itemCls = value;
    }
    private javax.el.ValueExpression labelSeparator;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setLabelSeparator(javax.el.ValueExpression value) {
	this.labelSeparator = value;
    }
    private javax.el.ValueExpression labelStyle;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setLabelStyle(javax.el.ValueExpression value) {
	this.labelStyle = value;
    }
    private javax.el.ValueExpression msgFx;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMsgFx(javax.el.ValueExpression value) {
	this.msgFx = value;
    }
    private javax.el.ValueExpression msgTarget;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMsgTarget(javax.el.ValueExpression value) {
	this.msgTarget = value;
    }
    private javax.el.ValueExpression name;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setName(javax.el.ValueExpression value) {
	this.name = value;
    }
    private javax.el.ValueExpression readOnly;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setReadOnly(javax.el.ValueExpression value) {
	this.readOnly = value;
    }
    private javax.el.ValueExpression tabIndex;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setTabIndex(javax.el.ValueExpression value) {
	this.tabIndex = value;
    }
    private javax.el.ValueExpression validateOnBlur;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setValidateOnBlur(javax.el.ValueExpression value) {
	this.validateOnBlur = value;
    }
    private javax.el.ValueExpression validationDelay;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setValidationDelay(javax.el.ValueExpression value) {
	this.validationDelay = value;
    }
    private javax.el.ValueExpression validationEvent;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setValidationEvent(javax.el.ValueExpression value) {
	this.validationEvent = value;
    }
    private javax.el.ValueExpression autoWidth;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoWidth(javax.el.ValueExpression value) {
	this.autoWidth = value;
    }
    private javax.el.ValueExpression autoHeight;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoHeight(javax.el.ValueExpression value) {
	this.autoHeight = value;
    }
    private javax.el.ValueExpression height;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setHeight(javax.el.ValueExpression value) {
	this.height = value;
    }
    private javax.el.ValueExpression width;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setWidth(javax.el.ValueExpression value) {
	this.width = value;
    }
    private javax.el.ValueExpression onfocus;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnfocus(javax.el.ValueExpression value) {
	this.onfocus = value;
    }
    private javax.el.ValueExpression onblur;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnblur(javax.el.ValueExpression value) {
	this.onblur = value;
    }
    private javax.el.ValueExpression onchange;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnchange(javax.el.ValueExpression value) {
	this.onchange = value;
    }
    private javax.el.ValueExpression ondisable;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOndisable(javax.el.ValueExpression value) {
	this.ondisable = value;
    }
    private javax.el.ValueExpression onenable;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnenable(javax.el.ValueExpression value) {
	this.onenable = value;
    }
    private javax.el.ValueExpression onshow;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnshow(javax.el.ValueExpression value) {
	this.onshow = value;
    }
    private javax.el.ValueExpression onhide;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnhide(javax.el.ValueExpression value) {
	this.onhide = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("autoCreate", this.autoCreate);
	c.setValueExpression("clearCls", this.clearCls);
	c.setValueExpression("cls", this.cls);
	c.setValueExpression("disabled", this.disabled);
	c.setValueExpression("fieldClass", this.fieldClass);
	c.setValueExpression("fieldLabel", this.fieldLabel);
	c.setValueExpression("focusClass", this.focusClass);
	c.setValueExpression("hideLabel", this.hideLabel);
	c.setValueExpression("inputType", this.inputType);
	c.setValueExpression("invalidClass", this.invalidClass);
	c.setValueExpression("invalidText", this.invalidText);
	c.setValueExpression("itemCls", this.itemCls);
	c.setValueExpression("labelSeparator", this.labelSeparator);
	c.setValueExpression("labelStyle", this.labelStyle);
	c.setValueExpression("msgFx", this.msgFx);
	c.setValueExpression("msgTarget", this.msgTarget);
	c.setValueExpression("name", this.name);
	c.setValueExpression("readOnly", this.readOnly);
	c.setValueExpression("tabIndex", this.tabIndex);
	c.setValueExpression("validateOnBlur", this.validateOnBlur);
	c.setValueExpression("validationDelay", this.validationDelay);
	c.setValueExpression("validationEvent", this.validationEvent);
	c.setValueExpression("autoWidth", this.autoWidth);
	c.setValueExpression("autoHeight", this.autoHeight);
	c.setValueExpression("height", this.height);
	c.setValueExpression("width", this.width);
	c.setValueExpression("onfocus", this.onfocus);
	c.setValueExpression("onblur", this.onblur);
	c.setValueExpression("onchange", this.onchange);
	c.setValueExpression("ondisable", this.ondisable);
	c.setValueExpression("onenable", this.onenable);
	c.setValueExpression("onshow", this.onshow);
	c.setValueExpression("onhide", this.onhide);
    }

    public void release() {
	super.release();
	this.autoCreate = null;
	this.clearCls = null;
	this.cls = null;
	this.disabled = null;
	this.fieldClass = null;
	this.fieldLabel = null;
	this.focusClass = null;
	this.hideLabel = null;
	this.inputType = null;
	this.invalidClass = null;
	this.invalidText = null;
	this.itemCls = null;
	this.labelSeparator = null;
	this.labelStyle = null;
	this.msgFx = null;
	this.msgTarget = null;
	this.name = null;
	this.readOnly = null;
	this.tabIndex = null;
	this.validateOnBlur = null;
	this.validationDelay = null;
	this.validationEvent = null;
	this.autoWidth = null;
	this.autoHeight = null;
	this.height = null;
	this.width = null;
	this.onfocus = null;
	this.onblur = null;
	this.onchange = null;
	this.ondisable = null;
	this.onenable = null;
	this.onshow = null;
	this.onhide = null;
    }

}
