/**
 * UINumberField.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

/**
* @jsp.tag name="numberField" body-content="JSP"
*/
public class UINumberFieldTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UINumberField";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UINumberField";
    }

    private javax.el.ValueExpression allowDecimals;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAllowDecimals(javax.el.ValueExpression value) {
	this.allowDecimals = value;
    }
    private javax.el.ValueExpression allowNegative;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAllowNegative(javax.el.ValueExpression value) {
	this.allowNegative = value;
    }
    private javax.el.ValueExpression baseChars;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setBaseChars(javax.el.ValueExpression value) {
	this.baseChars = value;
    }
    private javax.el.ValueExpression decimalPrecision;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setDecimalPrecision(javax.el.ValueExpression value) {
	this.decimalPrecision = value;
    }
    private javax.el.ValueExpression decimalSeparator;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setDecimalSeparator(javax.el.ValueExpression value) {
	this.decimalSeparator = value;
    }
    private javax.el.ValueExpression fieldClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFieldClass(javax.el.ValueExpression value) {
	this.fieldClass = value;
    }
    private javax.el.ValueExpression maxText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMaxText(javax.el.ValueExpression value) {
	this.maxText = value;
    }
    private javax.el.ValueExpression maxValue;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMaxValue(javax.el.ValueExpression value) {
	this.maxValue = value;
    }
    private javax.el.ValueExpression minText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMinText(javax.el.ValueExpression value) {
	this.minText = value;
    }
    private javax.el.ValueExpression minValue;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMinValue(javax.el.ValueExpression value) {
	this.minValue = value;
    }
    private javax.el.ValueExpression nanText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setNanText(javax.el.ValueExpression value) {
	this.nanText = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("allowDecimals", this.allowDecimals);
	c.setValueExpression("allowNegative", this.allowNegative);
	c.setValueExpression("baseChars", this.baseChars);
	c.setValueExpression("decimalPrecision", this.decimalPrecision);
	c.setValueExpression("decimalSeparator", this.decimalSeparator);
	c.setValueExpression("fieldClass", this.fieldClass);
	c.setValueExpression("maxText", this.maxText);
	c.setValueExpression("maxValue", this.maxValue);
	c.setValueExpression("minText", this.minText);
	c.setValueExpression("minValue", this.minValue);
	c.setValueExpression("nanText", this.nanText);
    }

    public void release() {
	super.release();
	this.allowDecimals = null;
	this.allowNegative = null;
	this.baseChars = null;
	this.decimalPrecision = null;
	this.decimalSeparator = null;
	this.fieldClass = null;
	this.maxText = null;
	this.maxValue = null;
	this.minText = null;
	this.minValue = null;
	this.nanText = null;
    }

}
