/**
 * UISimpleHtmlEditor.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

/**
* @jsp.tag name="simpleHtmlEditor" body-content="JSP"
*/
public class UISimpleHtmlEditorTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UISimpleHtmlEditor";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UISimpleHtmlEditor";
    }

    private javax.el.ValueExpression createLinkText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setCreateLinkText(javax.el.ValueExpression value) {
	this.createLinkText = value;
    }
    private javax.el.ValueExpression defaultLinkValue;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setDefaultLinkValue(javax.el.ValueExpression value) {
	this.defaultLinkValue = value;
    }
    private javax.el.ValueExpression enableAlignments;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableAlignments(javax.el.ValueExpression value) {
	this.enableAlignments = value;
    }
    private javax.el.ValueExpression enableColors;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableColors(javax.el.ValueExpression value) {
	this.enableColors = value;
    }
    private javax.el.ValueExpression enableFont;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableFont(javax.el.ValueExpression value) {
	this.enableFont = value;
    }
    private javax.el.ValueExpression enableFontSize;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableFontSize(javax.el.ValueExpression value) {
	this.enableFontSize = value;
    }
    private javax.el.ValueExpression enableFormat;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableFormat(javax.el.ValueExpression value) {
	this.enableFormat = value;
    }
    private javax.el.ValueExpression enableLinks;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableLinks(javax.el.ValueExpression value) {
	this.enableLinks = value;
    }
    private javax.el.ValueExpression enableLists;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableLists(javax.el.ValueExpression value) {
	this.enableLists = value;
    }
    private javax.el.ValueExpression enableSourceEdit;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableSourceEdit(javax.el.ValueExpression value) {
	this.enableSourceEdit = value;
    }
    private javax.el.ValueExpression fontFamilies;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFontFamilies(javax.el.ValueExpression value) {
	this.fontFamilies = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("createLinkText", this.createLinkText);
	c.setValueExpression("defaultLinkValue", this.defaultLinkValue);
	c.setValueExpression("enableAlignments", this.enableAlignments);
	c.setValueExpression("enableColors", this.enableColors);
	c.setValueExpression("enableFont", this.enableFont);
	c.setValueExpression("enableFontSize", this.enableFontSize);
	c.setValueExpression("enableFormat", this.enableFormat);
	c.setValueExpression("enableLinks", this.enableLinks);
	c.setValueExpression("enableLists", this.enableLists);
	c.setValueExpression("enableSourceEdit", this.enableSourceEdit);
	c.setValueExpression("fontFamilies", this.fontFamilies);
    }

    public void release() {
	super.release();
	this.createLinkText = null;
	this.defaultLinkValue = null;
	this.enableAlignments = null;
	this.enableColors = null;
	this.enableFont = null;
	this.enableFontSize = null;
	this.enableFormat = null;
	this.enableLinks = null;
	this.enableLists = null;
	this.enableSourceEdit = null;
	this.fontFamilies = null;
    }

}
