/**
 * UITextArea.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

/**
* @jsp.tag name="textArea" body-content="JSP"
*/
public class UITextAreaTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UITextArea";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UITextArea";
    }

    private javax.el.ValueExpression growMax;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setGrowMax(javax.el.ValueExpression value) {
	this.growMax = value;
    }
    private javax.el.ValueExpression growMin;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setGrowMin(javax.el.ValueExpression value) {
	this.growMin = value;
    }
    private javax.el.ValueExpression preventScrollbars;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setPreventScrollbars(javax.el.ValueExpression value) {
	this.preventScrollbars = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("growMax", this.growMax);
	c.setValueExpression("growMin", this.growMin);
	c.setValueExpression("preventScrollbars", this.preventScrollbars);
    }

    public void release() {
	super.release();
	this.growMax = null;
	this.growMin = null;
	this.preventScrollbars = null;
    }

}
