/**
 * UITextField.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

/**
* @jsp.tag name="textField" body-content="JSP"
*/
public class UITextFieldTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UITextField";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UITextField";
    }

    private javax.el.ValueExpression allowBlank;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAllowBlank(javax.el.ValueExpression value) {
	this.allowBlank = value;
    }
    private javax.el.ValueExpression blankText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setBlankText(javax.el.ValueExpression value) {
	this.blankText = value;
    }
    private javax.el.ValueExpression disableKeyFilter;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setDisableKeyFilter(javax.el.ValueExpression value) {
	this.disableKeyFilter = value;
    }
    private javax.el.ValueExpression emptyClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setEmptyClass(javax.el.ValueExpression value) {
	this.emptyClass = value;
    }
    private javax.el.ValueExpression emptyText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setEmptyText(javax.el.ValueExpression value) {
	this.emptyText = value;
    }
    private javax.el.ValueExpression grow;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setGrow(javax.el.ValueExpression value) {
	this.grow = value;
    }
    private javax.el.ValueExpression growMax;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setGrowMax(javax.el.ValueExpression value) {
	this.growMax = value;
    }
    private javax.el.ValueExpression growMin;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setGrowMin(javax.el.ValueExpression value) {
	this.growMin = value;
    }
    private javax.el.ValueExpression maskRe;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMaskRe(javax.el.ValueExpression value) {
	this.maskRe = value;
    }
    private javax.el.ValueExpression maxLength;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMaxLength(javax.el.ValueExpression value) {
	this.maxLength = value;
    }
    private javax.el.ValueExpression maxLengthText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMaxLengthText(javax.el.ValueExpression value) {
	this.maxLengthText = value;
    }
    private javax.el.ValueExpression minLength;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMinLength(javax.el.ValueExpression value) {
	this.minLength = value;
    }
    private javax.el.ValueExpression minLengthText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMinLengthText(javax.el.ValueExpression value) {
	this.minLengthText = value;
    }
    private javax.el.ValueExpression regex;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setRegex(javax.el.ValueExpression value) {
	this.regex = value;
    }
    private javax.el.ValueExpression regexText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setRegexText(javax.el.ValueExpression value) {
	this.regexText = value;
    }
    private javax.el.ValueExpression selectOnFocus;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setSelectOnFocus(javax.el.ValueExpression value) {
	this.selectOnFocus = value;
    }
    private javax.el.ValueExpression vtype;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setVtype(javax.el.ValueExpression value) {
	this.vtype = value;
    }
    private javax.el.ValueExpression vtypeText;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setVtypeText(javax.el.ValueExpression value) {
	this.vtypeText = value;
    }
    private javax.el.ValueExpression value;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setValue(javax.el.ValueExpression value) {
	this.value = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("allowBlank", this.allowBlank);
	c.setValueExpression("blankText", this.blankText);
	c.setValueExpression("disableKeyFilter", this.disableKeyFilter);
	c.setValueExpression("emptyClass", this.emptyClass);
	c.setValueExpression("emptyText", this.emptyText);
	c.setValueExpression("grow", this.grow);
	c.setValueExpression("growMax", this.growMax);
	c.setValueExpression("growMin", this.growMin);
	c.setValueExpression("maskRe", this.maskRe);
	c.setValueExpression("maxLength", this.maxLength);
	c.setValueExpression("maxLengthText", this.maxLengthText);
	c.setValueExpression("minLength", this.minLength);
	c.setValueExpression("minLengthText", this.minLengthText);
	c.setValueExpression("regex", this.regex);
	c.setValueExpression("regexText", this.regexText);
	c.setValueExpression("selectOnFocus", this.selectOnFocus);
	c.setValueExpression("vtype", this.vtype);
	c.setValueExpression("vtypeText", this.vtypeText);
	c.setValueExpression("value", this.value);
    }

    public void release() {
	super.release();
	this.allowBlank = null;
	this.blankText = null;
	this.disableKeyFilter = null;
	this.emptyClass = null;
	this.emptyText = null;
	this.grow = null;
	this.growMax = null;
	this.growMin = null;
	this.maskRe = null;
	this.maxLength = null;
	this.maxLengthText = null;
	this.minLength = null;
	this.minLengthText = null;
	this.regex = null;
	this.regexText = null;
	this.selectOnFocus = null;
	this.vtype = null;
	this.vtypeText = null;
	this.value = null;
    }

}
