/**
 * UITriggerField.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.form;

public class UITriggerFieldTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.form.impl.UITriggerField";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.form.impl.UITriggerField";
    }

    private javax.el.ValueExpression hideTrigger;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideTrigger(javax.el.ValueExpression value) {
	this.hideTrigger = value;
    }
    private javax.el.ValueExpression triggerClass;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTriggerClass(javax.el.ValueExpression value) {
	this.triggerClass = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("hideTrigger", this.hideTrigger);
	c.setValueExpression("triggerClass", this.triggerClass);
    }

    public void release() {
	super.release();
	this.hideTrigger = null;
	this.triggerClass = null;
    }

}
