/**
 * UIAccordionLayout.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.component.layout.impl;

import org.operamasks.faces.component.layout.base.UIAccordionLayoutBase;

@javax.annotation.Generated(value="org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory", date="2012-11-03T15:46:26Z")
public class UIAccordionLayout extends UIAccordionLayoutBase {
    public static final String COMPONENT_FAMILY = "org.operamasks.faces.component.layout.impl.UIAccordionLayout";
    public static final String COMPONENT_TYPE = "org.operamasks.faces.component.layout.impl.UIAccordionLayout";

    public UIAccordionLayout() {
	super.setRendererType("org.operamasks.faces.component.layout.impl.UIAccordionLayout");
    }

    public String getFamily() {
	return COMPONENT_FAMILY;
    }

    public java.lang.Boolean getTitleCollapse() {
	if (this.titleCollapse != null) {
	    return this.titleCollapse;
	}
	javax.el.ValueExpression ve = this.getValueExpression("titleCollapse");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setTitleCollapse(java.lang.Boolean value) {
	this.titleCollapse = value;
    }

    public java.lang.Boolean getAnimate() {
	if (this.animate != null) {
	    return this.animate;
	}
	javax.el.ValueExpression ve = this.getValueExpression("animate");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setAnimate(java.lang.Boolean value) {
	this.animate = value;
    }

    public java.lang.Boolean getActiveOnTop() {
	if (this.activeOnTop != null) {
	    return this.activeOnTop;
	}
	javax.el.ValueExpression ve = this.getValueExpression("activeOnTop");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setActiveOnTop(java.lang.Boolean value) {
	this.activeOnTop = value;
    }

    public Object saveState(javax.faces.context.FacesContext context) {
	return new Object[] {
	    super.saveState(context),
	    this.titleCollapse,
	    this.animate,
	    this.activeOnTop,
	};
    }

    public void restoreState(javax.faces.context.FacesContext context, Object state) {
	Object[] values = (Object[])state;
	super.restoreState(context, values[0]);
	this.titleCollapse = (java.lang.Boolean)values[1];
	this.animate = (java.lang.Boolean)values[2];
	this.activeOnTop = (java.lang.Boolean)values[3];
    }

}
