/**
 * UIBorderLayout.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.component.layout.impl;

import org.operamasks.faces.component.layout.base.UIBorderLayoutBase;

@javax.annotation.Generated(value="org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory", date="2012-11-03T15:46:26Z")
public class UIBorderLayout extends UIBorderLayoutBase {
    public static final String COMPONENT_FAMILY = "org.operamasks.faces.component.layout.impl.UIBorderLayout";
    public static final String COMPONENT_TYPE = "org.operamasks.faces.component.layout.impl.UIBorderLayout";

    public UIBorderLayout() {
	super.setRendererType("org.operamasks.faces.component.layout.impl.UIBorderLayout");
    }

    public String getFamily() {
	return COMPONENT_FAMILY;
    }

    public java.lang.Boolean getFitToBody() {
	if (this.fitToBody != null) {
	    return this.fitToBody;
	}
	javax.el.ValueExpression ve = this.getValueExpression("fitToBody");
	if (ve != null) {
	    try {
		return (java.lang.Boolean)ve.getValue(this.getFacesContext().getELContext());
	    } catch (javax.el.ELException e) {
		throw new javax.faces.FacesException(e);
	    }
	}
	return null;
    }

    public void setFitToBody(java.lang.Boolean value) {
	this.fitToBody = value;
    }

    public Object saveState(javax.faces.context.FacesContext context) {
	return new Object[] {
	    super.saveState(context),
	    this.fitToBody,
	};
    }

    public void restoreState(javax.faces.context.FacesContext context, Object state) {
	Object[] values = (Object[])state;
	super.restoreState(context, values[0]);
	this.fitToBody = (java.lang.Boolean)values[1];
    }

}
