/**
 * UICardLayout.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.layout;

/**
* @jsp.tag name="cardLayout" body-content="JSP"
*/
public class UICardLayoutTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.layout.impl.UICardLayout";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.layout.impl.UICardLayout";
    }

    private javax.el.ValueExpression activeItem;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setActiveItem(javax.el.ValueExpression value) {
	this.activeItem = value;
    }
    private javax.el.ValueExpression deferredRender;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setDeferredRender(javax.el.ValueExpression value) {
	this.deferredRender = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("activeItem", this.activeItem);
	c.setValueExpression("deferredRender", this.deferredRender);
    }

    public void release() {
	super.release();
	this.activeItem = null;
	this.deferredRender = null;
    }

}
