/**
 * UIColumnLayout.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.layout;

/**
* @jsp.tag name="columnLayout" body-content="JSP"
*/
public class UIColumnLayoutTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.layout.impl.UIColumnLayout";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.layout.impl.UIColumnLayout";
    }

    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
    }

    public void release() {
	super.release();
    }

}
