/**
 * UIPanel.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.layout;

/**
* @jsp.tag name="panel" body-content="JSP"
*/
public class UIPanelTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.layout.impl.UIPanel";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.layout.impl.UIPanel";
    }

    private javax.el.ValueExpression animCollapse;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAnimCollapse(javax.el.ValueExpression value) {
	this.animCollapse = value;
    }
    private javax.el.ValueExpression autoHeight;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoHeight(javax.el.ValueExpression value) {
	this.autoHeight = value;
    }
    private javax.el.ValueExpression autoScroll;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoScroll(javax.el.ValueExpression value) {
	this.autoScroll = value;
    }
    private javax.el.ValueExpression autoShow;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoShow(javax.el.ValueExpression value) {
	this.autoShow = value;
    }
    private javax.el.ValueExpression autoWidth;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoWidth(javax.el.ValueExpression value) {
	this.autoWidth = value;
    }
    private javax.el.ValueExpression bodyBorder;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setBodyBorder(javax.el.ValueExpression value) {
	this.bodyBorder = value;
    }
    private javax.el.ValueExpression bodyStyle;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setBodyStyle(javax.el.ValueExpression value) {
	this.bodyStyle = value;
    }
    private javax.el.ValueExpression border;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setBorder(javax.el.ValueExpression value) {
	this.border = value;
    }
    private javax.el.ValueExpression collapseFirst;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setCollapseFirst(javax.el.ValueExpression value) {
	this.collapseFirst = value;
    }
    private javax.el.ValueExpression collapsed;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setCollapsed(javax.el.ValueExpression value) {
	this.collapsed = value;
    }
    private javax.el.ValueExpression collapsible;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setCollapsible(javax.el.ValueExpression value) {
	this.collapsible = value;
    }
    private javax.el.ValueExpression draggable;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setDraggable(javax.el.ValueExpression value) {
	this.draggable = value;
    }
    private javax.el.ValueExpression floating;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setFloating(javax.el.ValueExpression value) {
	this.floating = value;
    }
    private javax.el.ValueExpression footer;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setFooter(javax.el.ValueExpression value) {
	this.footer = value;
    }
    private javax.el.ValueExpression frame;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setFrame(javax.el.ValueExpression value) {
	this.frame = value;
    }
    private javax.el.ValueExpression header;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHeader(javax.el.ValueExpression value) {
	this.header = value;
    }
    private javax.el.ValueExpression headerAsText;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHeaderAsText(javax.el.ValueExpression value) {
	this.headerAsText = value;
    }
    private javax.el.ValueExpression height;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setHeight(javax.el.ValueExpression value) {
	this.height = value;
    }
    private javax.el.ValueExpression hideBorders;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideBorders(javax.el.ValueExpression value) {
	this.hideBorders = value;
    }
    private javax.el.ValueExpression hideCollapseTool;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideCollapseTool(javax.el.ValueExpression value) {
	this.hideCollapseTool = value;
    }
    private javax.el.ValueExpression hideParent;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideParent(javax.el.ValueExpression value) {
	this.hideParent = value;
    }
    private javax.el.ValueExpression layout;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setLayout(javax.el.ValueExpression value) {
	this.layout = value;
    }
    private javax.el.ValueExpression maskDisabled;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setMaskDisabled(javax.el.ValueExpression value) {
	this.maskDisabled = value;
    }
    private javax.el.ValueExpression shadow;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setShadow(javax.el.ValueExpression value) {
	this.shadow = value;
    }
    private javax.el.ValueExpression shadowOffset;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setShadowOffset(javax.el.ValueExpression value) {
	this.shadowOffset = value;
    }
    private javax.el.ValueExpression shim;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setShim(javax.el.ValueExpression value) {
	this.shim = value;
    }
    private javax.el.ValueExpression title;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTitle(javax.el.ValueExpression value) {
	this.title = value;
    }
    private javax.el.ValueExpression titleCollapse;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setTitleCollapse(javax.el.ValueExpression value) {
	this.titleCollapse = value;
    }
    private javax.el.ValueExpression width;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setWidth(javax.el.ValueExpression value) {
	this.width = value;
    }
    private javax.el.ValueExpression animFloat;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAnimFloat(javax.el.ValueExpression value) {
	this.animFloat = value;
    }
    private javax.el.ValueExpression autoHide;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoHide(javax.el.ValueExpression value) {
	this.autoHide = value;
    }
    private javax.el.ValueExpression cmargins;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setCmargins(javax.el.ValueExpression value) {
	this.cmargins = value;
    }
    private javax.el.ValueExpression collapseMode;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setCollapseMode(javax.el.ValueExpression value) {
	this.collapseMode = value;
    }
    private javax.el.ValueExpression floatable;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setFloatable(javax.el.ValueExpression value) {
	this.floatable = value;
    }
    private javax.el.ValueExpression margins;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setMargins(javax.el.ValueExpression value) {
	this.margins = value;
    }
    private javax.el.ValueExpression region;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setRegion(javax.el.ValueExpression value) {
	this.region = value;
    }
    private javax.el.ValueExpression minSize;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMinSize(javax.el.ValueExpression value) {
	this.minSize = value;
    }
    private javax.el.ValueExpression maxSize;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMaxSize(javax.el.ValueExpression value) {
	this.maxSize = value;
    }
    private javax.el.ValueExpression split;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setSplit(javax.el.ValueExpression value) {
	this.split = value;
    }
    private javax.el.ValueExpression columnWidth;
    /**
    * @jsp.attribute type="java.lang.Float"
    */
    public void setColumnWidth(javax.el.ValueExpression value) {
	this.columnWidth = value;
    }
    private javax.el.ValueExpression rowspan;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setRowspan(javax.el.ValueExpression value) {
	this.rowspan = value;
    }
    private javax.el.ValueExpression colspan;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setColspan(javax.el.ValueExpression value) {
	this.colspan = value;
    }
    private javax.el.ValueExpression x;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setX(javax.el.ValueExpression value) {
	this.x = value;
    }
    private javax.el.ValueExpression y;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setY(javax.el.ValueExpression value) {
	this.y = value;
    }
    private javax.el.ValueExpression closable;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setClosable(javax.el.ValueExpression value) {
	this.closable = value;
    }
    private javax.el.ValueExpression onactivate;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnactivate(javax.el.ValueExpression value) {
	this.onactivate = value;
    }
    private javax.el.ValueExpression jsvar;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setJsvar(javax.el.ValueExpression value) {
	this.jsvar = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("animCollapse", this.animCollapse);
	c.setValueExpression("autoHeight", this.autoHeight);
	c.setValueExpression("autoScroll", this.autoScroll);
	c.setValueExpression("autoShow", this.autoShow);
	c.setValueExpression("autoWidth", this.autoWidth);
	c.setValueExpression("bodyBorder", this.bodyBorder);
	c.setValueExpression("bodyStyle", this.bodyStyle);
	c.setValueExpression("border", this.border);
	c.setValueExpression("collapseFirst", this.collapseFirst);
	c.setValueExpression("collapsed", this.collapsed);
	c.setValueExpression("collapsible", this.collapsible);
	c.setValueExpression("draggable", this.draggable);
	c.setValueExpression("floating", this.floating);
	c.setValueExpression("footer", this.footer);
	c.setValueExpression("frame", this.frame);
	c.setValueExpression("header", this.header);
	c.setValueExpression("headerAsText", this.headerAsText);
	c.setValueExpression("height", this.height);
	c.setValueExpression("hideBorders", this.hideBorders);
	c.setValueExpression("hideCollapseTool", this.hideCollapseTool);
	c.setValueExpression("hideParent", this.hideParent);
	c.setValueExpression("layout", this.layout);
	c.setValueExpression("maskDisabled", this.maskDisabled);
	c.setValueExpression("shadow", this.shadow);
	c.setValueExpression("shadowOffset", this.shadowOffset);
	c.setValueExpression("shim", this.shim);
	c.setValueExpression("title", this.title);
	c.setValueExpression("titleCollapse", this.titleCollapse);
	c.setValueExpression("width", this.width);
	c.setValueExpression("animFloat", this.animFloat);
	c.setValueExpression("autoHide", this.autoHide);
	c.setValueExpression("cmargins", this.cmargins);
	c.setValueExpression("collapseMode", this.collapseMode);
	c.setValueExpression("floatable", this.floatable);
	c.setValueExpression("margins", this.margins);
	c.setValueExpression("region", this.region);
	c.setValueExpression("minSize", this.minSize);
	c.setValueExpression("maxSize", this.maxSize);
	c.setValueExpression("split", this.split);
	c.setValueExpression("columnWidth", this.columnWidth);
	c.setValueExpression("rowspan", this.rowspan);
	c.setValueExpression("colspan", this.colspan);
	c.setValueExpression("x", this.x);
	c.setValueExpression("y", this.y);
	c.setValueExpression("closable", this.closable);
	c.setValueExpression("onactivate", this.onactivate);
	c.setValueExpression("jsvar", this.jsvar);
    }

    public void release() {
	super.release();
	this.animCollapse = null;
	this.autoHeight = null;
	this.autoScroll = null;
	this.autoShow = null;
	this.autoWidth = null;
	this.bodyBorder = null;
	this.bodyStyle = null;
	this.border = null;
	this.collapseFirst = null;
	this.collapsed = null;
	this.collapsible = null;
	this.draggable = null;
	this.floating = null;
	this.footer = null;
	this.frame = null;
	this.header = null;
	this.headerAsText = null;
	this.height = null;
	this.hideBorders = null;
	this.hideCollapseTool = null;
	this.hideParent = null;
	this.layout = null;
	this.maskDisabled = null;
	this.shadow = null;
	this.shadowOffset = null;
	this.shim = null;
	this.title = null;
	this.titleCollapse = null;
	this.width = null;
	this.animFloat = null;
	this.autoHide = null;
	this.cmargins = null;
	this.collapseMode = null;
	this.floatable = null;
	this.margins = null;
	this.region = null;
	this.minSize = null;
	this.maxSize = null;
	this.split = null;
	this.columnWidth = null;
	this.rowspan = null;
	this.colspan = null;
	this.x = null;
	this.y = null;
	this.closable = null;
	this.onactivate = null;
	this.jsvar = null;
    }

}
