/**
 * UITabLayout.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.layout;

/**
* @jsp.tag name="tabLayout" body-content="JSP"
*/
public class UITabLayoutTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.layout.impl.UITabLayout";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.layout.impl.UITabLayout";
    }

    private javax.el.ValueExpression activeTab;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setActiveTab(javax.el.ValueExpression value) {
	this.activeTab = value;
    }
    private javax.el.ValueExpression animScroll;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAnimScroll(javax.el.ValueExpression value) {
	this.animScroll = value;
    }
    private javax.el.ValueExpression autoTabSelector;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setAutoTabSelector(javax.el.ValueExpression value) {
	this.autoTabSelector = value;
    }
    private javax.el.ValueExpression autoTabs;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoTabs(javax.el.ValueExpression value) {
	this.autoTabs = value;
    }
    private javax.el.ValueExpression deferredRender;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setDeferredRender(javax.el.ValueExpression value) {
	this.deferredRender = value;
    }
    private javax.el.ValueExpression enableTabScroll;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setEnableTabScroll(javax.el.ValueExpression value) {
	this.enableTabScroll = value;
    }
    private javax.el.ValueExpression minTabWidth;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setMinTabWidth(javax.el.ValueExpression value) {
	this.minTabWidth = value;
    }
    private javax.el.ValueExpression monitorResize;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setMonitorResize(javax.el.ValueExpression value) {
	this.monitorResize = value;
    }
    private javax.el.ValueExpression plain;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setPlain(javax.el.ValueExpression value) {
	this.plain = value;
    }
    private javax.el.ValueExpression resizeTabs;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setResizeTabs(javax.el.ValueExpression value) {
	this.resizeTabs = value;
    }
    private javax.el.ValueExpression scrollDuration;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setScrollDuration(javax.el.ValueExpression value) {
	this.scrollDuration = value;
    }
    private javax.el.ValueExpression scrollIncrement;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setScrollIncrement(javax.el.ValueExpression value) {
	this.scrollIncrement = value;
    }
    private javax.el.ValueExpression scrollRepeatInterval;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setScrollRepeatInterval(javax.el.ValueExpression value) {
	this.scrollRepeatInterval = value;
    }
    private javax.el.ValueExpression tabMargin;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setTabMargin(javax.el.ValueExpression value) {
	this.tabMargin = value;
    }
    private javax.el.ValueExpression tabPosition;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTabPosition(javax.el.ValueExpression value) {
	this.tabPosition = value;
    }
    private javax.el.ValueExpression tabWidth;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setTabWidth(javax.el.ValueExpression value) {
	this.tabWidth = value;
    }
    private javax.el.ValueExpression wheelIncrement;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setWheelIncrement(javax.el.ValueExpression value) {
	this.wheelIncrement = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("activeTab", this.activeTab);
	c.setValueExpression("animScroll", this.animScroll);
	c.setValueExpression("autoTabSelector", this.autoTabSelector);
	c.setValueExpression("autoTabs", this.autoTabs);
	c.setValueExpression("deferredRender", this.deferredRender);
	c.setValueExpression("enableTabScroll", this.enableTabScroll);
	c.setValueExpression("minTabWidth", this.minTabWidth);
	c.setValueExpression("monitorResize", this.monitorResize);
	c.setValueExpression("plain", this.plain);
	c.setValueExpression("resizeTabs", this.resizeTabs);
	c.setValueExpression("scrollDuration", this.scrollDuration);
	c.setValueExpression("scrollIncrement", this.scrollIncrement);
	c.setValueExpression("scrollRepeatInterval", this.scrollRepeatInterval);
	c.setValueExpression("tabMargin", this.tabMargin);
	c.setValueExpression("tabPosition", this.tabPosition);
	c.setValueExpression("tabWidth", this.tabWidth);
	c.setValueExpression("wheelIncrement", this.wheelIncrement);
    }

    public void release() {
	super.release();
	this.activeTab = null;
	this.animScroll = null;
	this.autoTabSelector = null;
	this.autoTabs = null;
	this.deferredRender = null;
	this.enableTabScroll = null;
	this.minTabWidth = null;
	this.monitorResize = null;
	this.plain = null;
	this.resizeTabs = null;
	this.scrollDuration = null;
	this.scrollIncrement = null;
	this.scrollRepeatInterval = null;
	this.tabMargin = null;
	this.tabPosition = null;
	this.tabWidth = null;
	this.wheelIncrement = null;
    }

}
