/**
 * UITableLayout.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.layout;

/**
* @jsp.tag name="tableLayout" body-content="JSP"
*/
public class UITableLayoutTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.layout.impl.UITableLayout";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.layout.impl.UITableLayout";
    }

    private javax.el.ValueExpression columns;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setColumns(javax.el.ValueExpression value) {
	this.columns = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("columns", this.columns);
    }

    public void release() {
	super.release();
	this.columns = null;
    }

}
