/**
 * UIIFrame.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:26 CST 2012
 */

package org.operamasks.faces.webapp.widget;

/**
* @jsp.tag name="iframe" body-content="JSP"
*/
public class UIIFrameTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.html.impl.UIIFrame";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.html.impl.UIIFrame";
    }

    private javax.el.ValueExpression align;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setAlign(javax.el.ValueExpression value) {
	this.align = value;
    }
    private javax.el.ValueExpression border;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setBorder(javax.el.ValueExpression value) {
	this.border = value;
    }
    private javax.el.ValueExpression width;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setWidth(javax.el.ValueExpression value) {
	this.width = value;
    }
    private javax.el.ValueExpression height;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setHeight(javax.el.ValueExpression value) {
	this.height = value;
    }
    private javax.el.ValueExpression frameborder;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setFrameborder(javax.el.ValueExpression value) {
	this.frameborder = value;
    }
    private javax.el.ValueExpression name;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setName(javax.el.ValueExpression value) {
	this.name = value;
    }
    private javax.el.ValueExpression scrolling;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setScrolling(javax.el.ValueExpression value) {
	this.scrolling = value;
    }
    private javax.el.ValueExpression src;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setSrc(javax.el.ValueExpression value) {
	this.src = value;
    }
    private javax.el.ValueExpression style;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setStyle(javax.el.ValueExpression value) {
	this.style = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("align", this.align);
	c.setValueExpression("border", this.border);
	c.setValueExpression("width", this.width);
	c.setValueExpression("height", this.height);
	c.setValueExpression("frameborder", this.frameborder);
	c.setValueExpression("name", this.name);
	c.setValueExpression("scrolling", this.scrolling);
	c.setValueExpression("src", this.src);
	c.setValueExpression("style", this.style);
    }

    public void release() {
	super.release();
	this.align = null;
	this.border = null;
	this.width = null;
	this.height = null;
	this.frameborder = null;
	this.name = null;
	this.scrolling = null;
	this.src = null;
	this.style = null;
    }

}
