/**
 * UITree.java
 * DO NOT EDIT THIS FILE
 * This file was automatically generated by org.operamasks.faces.tools.apt.ComponentAnnotationProcessorFactory
 * at Sat Nov 03 15:46:27 CST 2012
 */

package org.operamasks.faces.webapp.widget;

/**
* @jsp.tag name="myTree" body-content="JSP"
*/
public class UITreeTag extends org.operamasks.faces.webapp.html.HtmlBasicELTag {
    public String getComponentType() {
	return "org.operamasks.faces.component.tree.impl.UITree";
    }

    public String getRendererType() {
	return "org.operamasks.faces.component.tree.impl.UITree";
    }

    private javax.el.ValueExpression animCollapse;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAnimCollapse(javax.el.ValueExpression value) {
	this.animCollapse = value;
    }
    private javax.el.ValueExpression autoHeight;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoHeight(javax.el.ValueExpression value) {
	this.autoHeight = value;
    }
    private javax.el.ValueExpression autoScroll;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoScroll(javax.el.ValueExpression value) {
	this.autoScroll = value;
    }
    private javax.el.ValueExpression autoShow;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoShow(javax.el.ValueExpression value) {
	this.autoShow = value;
    }
    private javax.el.ValueExpression autoWidth;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAutoWidth(javax.el.ValueExpression value) {
	this.autoWidth = value;
    }
    private javax.el.ValueExpression bodyBorder;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setBodyBorder(javax.el.ValueExpression value) {
	this.bodyBorder = value;
    }
    private javax.el.ValueExpression bodyStyle;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setBodyStyle(javax.el.ValueExpression value) {
	this.bodyStyle = value;
    }
    private javax.el.ValueExpression border;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setBorder(javax.el.ValueExpression value) {
	this.border = value;
    }
    private javax.el.ValueExpression collapseFirst;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setCollapseFirst(javax.el.ValueExpression value) {
	this.collapseFirst = value;
    }
    private javax.el.ValueExpression collapsed;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setCollapsed(javax.el.ValueExpression value) {
	this.collapsed = value;
    }
    private javax.el.ValueExpression collapsible;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setCollapsible(javax.el.ValueExpression value) {
	this.collapsible = value;
    }
    private javax.el.ValueExpression draggable;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setDraggable(javax.el.ValueExpression value) {
	this.draggable = value;
    }
    private javax.el.ValueExpression floating;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setFloating(javax.el.ValueExpression value) {
	this.floating = value;
    }
    private javax.el.ValueExpression footer;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setFooter(javax.el.ValueExpression value) {
	this.footer = value;
    }
    private javax.el.ValueExpression frame;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setFrame(javax.el.ValueExpression value) {
	this.frame = value;
    }
    private javax.el.ValueExpression header;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHeader(javax.el.ValueExpression value) {
	this.header = value;
    }
    private javax.el.ValueExpression headerAsText;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHeaderAsText(javax.el.ValueExpression value) {
	this.headerAsText = value;
    }
    private javax.el.ValueExpression height;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setHeight(javax.el.ValueExpression value) {
	this.height = value;
    }
    private javax.el.ValueExpression hideBorders;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideBorders(javax.el.ValueExpression value) {
	this.hideBorders = value;
    }
    private javax.el.ValueExpression hideCollapseTool;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideCollapseTool(javax.el.ValueExpression value) {
	this.hideCollapseTool = value;
    }
    private javax.el.ValueExpression hideParent;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setHideParent(javax.el.ValueExpression value) {
	this.hideParent = value;
    }
    private javax.el.ValueExpression layout;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setLayout(javax.el.ValueExpression value) {
	this.layout = value;
    }
    private javax.el.ValueExpression maskDisabled;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setMaskDisabled(javax.el.ValueExpression value) {
	this.maskDisabled = value;
    }
    private javax.el.ValueExpression shadow;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setShadow(javax.el.ValueExpression value) {
	this.shadow = value;
    }
    private javax.el.ValueExpression shadowOffset;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setShadowOffset(javax.el.ValueExpression value) {
	this.shadowOffset = value;
    }
    private javax.el.ValueExpression shim;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setShim(javax.el.ValueExpression value) {
	this.shim = value;
    }
    private javax.el.ValueExpression title;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setTitle(javax.el.ValueExpression value) {
	this.title = value;
    }
    private javax.el.ValueExpression titleCollapse;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setTitleCollapse(javax.el.ValueExpression value) {
	this.titleCollapse = value;
    }
    private javax.el.ValueExpression width;
    /**
    * @jsp.attribute type="java.lang.Integer"
    */
    public void setWidth(javax.el.ValueExpression value) {
	this.width = value;
    }
    private javax.el.ValueExpression animate;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setAnimate(javax.el.ValueExpression value) {
	this.animate = value;
    }
    private javax.el.ValueExpression containerScroll;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setContainerScroll(javax.el.ValueExpression value) {
	this.containerScroll = value;
    }
    private javax.el.ValueExpression hlColor;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setHlColor(javax.el.ValueExpression value) {
	this.hlColor = value;
    }
    private javax.el.ValueExpression rootVisible;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setRootVisible(javax.el.ValueExpression value) {
	this.rootVisible = value;
    }
    private javax.el.ValueExpression value;
    /**
    * @jsp.attribute type="org.operamasks.faces.component.tree.base.TreeDataProvider"
    */
    public void setValue(javax.el.ValueExpression value) {
	this.value = value;
    }
    private javax.el.ValueExpression oncheck;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOncheck(javax.el.ValueExpression value) {
	this.oncheck = value;
    }
    private javax.el.ValueExpression onclick;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnclick(javax.el.ValueExpression value) {
	this.onclick = value;
    }
    private javax.el.ValueExpression oncollapsenode;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOncollapsenode(javax.el.ValueExpression value) {
	this.oncollapsenode = value;
    }
    private javax.el.ValueExpression onexpandnode;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setOnexpandnode(javax.el.ValueExpression value) {
	this.onexpandnode = value;
    }
    private javax.el.ValueExpression saveState;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setSaveState(javax.el.ValueExpression value) {
	this.saveState = value;
    }
    private javax.el.ValueExpression expandedNodes;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setExpandedNodes(javax.el.ValueExpression value) {
	this.expandedNodes = value;
    }
    private javax.el.ValueExpression loadAllNodes;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setLoadAllNodes(javax.el.ValueExpression value) {
	this.loadAllNodes = value;
    }
    private javax.el.ValueExpression expandAll;
    /**
    * @jsp.attribute type="java.lang.Boolean"
    */
    public void setExpandAll(javax.el.ValueExpression value) {
	this.expandAll = value;
    }
    private javax.el.ValueExpression eventName;
    /**
    * @jsp.attribute type="java.lang.String"
    */
    public void setEventName(javax.el.ValueExpression value) {
	this.eventName = value;
    }
    private javax.el.ValueExpression eventNode;
    /**
    * @jsp.attribute type="UITreeNode"
    */
    public void setEventNode(javax.el.ValueExpression value) {
	this.eventNode = value;
    }
    private javax.el.ValueExpression selectedNode;
    /**
    * @jsp.attribute type="UITreeNode"
    */
    public void setSelectedNode(javax.el.ValueExpression value) {
	this.selectedNode = value;
    }
    protected void setProperties(javax.faces.component.UIComponent c) {
	super.setProperties(c);
	c.setValueExpression("animCollapse", this.animCollapse);
	c.setValueExpression("autoHeight", this.autoHeight);
	c.setValueExpression("autoScroll", this.autoScroll);
	c.setValueExpression("autoShow", this.autoShow);
	c.setValueExpression("autoWidth", this.autoWidth);
	c.setValueExpression("bodyBorder", this.bodyBorder);
	c.setValueExpression("bodyStyle", this.bodyStyle);
	c.setValueExpression("border", this.border);
	c.setValueExpression("collapseFirst", this.collapseFirst);
	c.setValueExpression("collapsed", this.collapsed);
	c.setValueExpression("collapsible", this.collapsible);
	c.setValueExpression("draggable", this.draggable);
	c.setValueExpression("floating", this.floating);
	c.setValueExpression("footer", this.footer);
	c.setValueExpression("frame", this.frame);
	c.setValueExpression("header", this.header);
	c.setValueExpression("headerAsText", this.headerAsText);
	c.setValueExpression("height", this.height);
	c.setValueExpression("hideBorders", this.hideBorders);
	c.setValueExpression("hideCollapseTool", this.hideCollapseTool);
	c.setValueExpression("hideParent", this.hideParent);
	c.setValueExpression("layout", this.layout);
	c.setValueExpression("maskDisabled", this.maskDisabled);
	c.setValueExpression("shadow", this.shadow);
	c.setValueExpression("shadowOffset", this.shadowOffset);
	c.setValueExpression("shim", this.shim);
	c.setValueExpression("title", this.title);
	c.setValueExpression("titleCollapse", this.titleCollapse);
	c.setValueExpression("width", this.width);
	c.setValueExpression("animate", this.animate);
	c.setValueExpression("containerScroll", this.containerScroll);
	c.setValueExpression("hlColor", this.hlColor);
	c.setValueExpression("rootVisible", this.rootVisible);
	c.setValueExpression("value", this.value);
	c.setValueExpression("oncheck", this.oncheck);
	c.setValueExpression("onclick", this.onclick);
	c.setValueExpression("oncollapsenode", this.oncollapsenode);
	c.setValueExpression("onexpandnode", this.onexpandnode);
	c.setValueExpression("saveState", this.saveState);
	c.setValueExpression("expandedNodes", this.expandedNodes);
	c.setValueExpression("loadAllNodes", this.loadAllNodes);
	c.setValueExpression("expandAll", this.expandAll);
	c.setValueExpression("eventName", this.eventName);
	c.setValueExpression("eventNode", this.eventNode);
	c.setValueExpression("selectedNode", this.selectedNode);
    }

    public void release() {
	super.release();
	this.animCollapse = null;
	this.autoHeight = null;
	this.autoScroll = null;
	this.autoShow = null;
	this.autoWidth = null;
	this.bodyBorder = null;
	this.bodyStyle = null;
	this.border = null;
	this.collapseFirst = null;
	this.collapsed = null;
	this.collapsible = null;
	this.draggable = null;
	this.floating = null;
	this.footer = null;
	this.frame = null;
	this.header = null;
	this.headerAsText = null;
	this.height = null;
	this.hideBorders = null;
	this.hideCollapseTool = null;
	this.hideParent = null;
	this.layout = null;
	this.maskDisabled = null;
	this.shadow = null;
	this.shadowOffset = null;
	this.shim = null;
	this.title = null;
	this.titleCollapse = null;
	this.width = null;
	this.animate = null;
	this.containerScroll = null;
	this.hlColor = null;
	this.rootVisible = null;
	this.value = null;
	this.oncheck = null;
	this.onclick = null;
	this.oncollapsenode = null;
	this.onexpandnode = null;
	this.saveState = null;
	this.expandedNodes = null;
	this.loadAllNodes = null;
	this.expandAll = null;
	this.eventName = null;
	this.eventNode = null;
	this.selectedNode = null;
    }

}
